steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/k8s-node-app:$COMMIT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "eu.gcr.io/$PROJECT_ID/k8s-node-app:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/k8s-node-app
  - k8s-node-app=eu.gcr.io/$PROJECT_ID/k8s-node-app:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'